### PR TITLE
switch to geometrybasics

### PR DESCRIPTION
**Pull request by SimonDanisch**
I had to increase the tolerances for the "respect origin", which I'm not sure why that should be because of the switch...
Also, I hope you don't mind the new API ;) 
In addition, I moved the `DistanceField` type here from `GeometryTypes`!

### CODE REVIEW

**Comment by sjkelly** [comment]
One thing also is that GeometryTypes and GeometryBasics are not actually core to this package anymore. We can support both with `import`, since the respective API is purely convience. The downside is that both GT and GB are brought in with this package. There are three options in my mind:
- This PR
- `import` both libraries and extend
- Create a wrapper library for each

I am not too worried about breakage because of Pkg3 and this has very few public dependencies. However I am somewhat worried about the people using this in private that we don't see (about ~400 pulls on a new release). The second option is implemented here:  https://github.com/JuliaGeometry/Meshing.jl/tree/sjk/geometrybasics2. This provides a softer transition and should mean both GeometryTypes and GeometryBasics can be used together. 

@SimonDanisch do you have plans to use Meshing as dependency somewhere?

**Comment by SimonDanisch** [comment]
>@SimonDanisch do you have plans to use Meshing as dependency somewhere?

Not really ;) 
Softer break would of course be nice, but I feel like with Pkg3 and upper limits being widely used by now, we should just break it... I don't really want anyone to continue using GeometryTypes :D 
Although, I should definitely work a bit on the documentation, to ease the switch...

**Comment by sjkelly** [comment]
I agree. In that case lets go with #71 which is non-breaking until we get everyone migrated, and get all the residual functionality from GT into the correct places.

I've also have been working on adding support for calculating normals and isocaps which is API breaking, so it would be nice to roll everything out at once.

**Comment by sjkelly** [comment]
I cleaned up #71 and added you as co-author. It should function the same as this branch, with everything coexisting for now.

**Comment by sjkelly** [comment]
See #71.

**Pull request closed without merging**
