### PR TITLE
[WIP] Add Naive Surface Nets

### PR DESCRIPTION
**Pull request by sjkelly**
This is based on the algorithm by Mikola Lysenko.

Currently I just have a very rough direct port to Julia without any optimizations or integrations into our API, but it does work. Ideally if this is well optimized it should be ~2x as fast as MarchingCubes.

image

### CODE REVIEW

**Comment by sjkelly** [comment]
With some optimizations I have got this down to be ~4x faster than Marching Tetrahedra without memory trade-off.

```
torus = SignedDistanceField(HyperRectangle(Vec(-2,-2,-2.),Vec(4,4,4.)), 0.01) do v
    (sqrt(v[1]^2+v[2]^2)-0.5)^2 + v[3]^2 - 0.1 # torus
end


torus_sn = HomogenousMesh(torus, NaiveSurfaceNets())
torus_mc = HomogenousMesh(torus, MarchingCubes())
torus_mt = HomogenousMesh(torus, MarchingTetrahedra())

@btime HomogenousMesh(torus, NaiveSurfaceNets())
  315.827 ms (43 allocations: 9.82 MiB)

@btime HomogenousMesh(torus, MarchingCubes())
  4.260 s (66 allocations: 33.00 MiB)

@btime HomogenousMesh(torus, MarchingTetrahedra())
  1.436 s (7217032 allocations: 800.33 MiB)

```

|                     | Time  | Allocations | Memory |
|---------------------|-------|-------------|--------|
| Naive Surface Nets  | 1     | 1           | 1      |
| Marching Cubes      | 13.5x | 1.5x        | 3.3x   |
| Marching Tetrahedra | 4.4x  | 167837x     | 81x    |

**Comment by rdeits** [comment]
Very cool, thanks! Would you be willing to add some tests to make sure the algorithm is returning a reasonable mesh (it clearly works now, but might break at some point in the future)? For example, perhaps your sphere test could check that every vertex in the resulting mesh is roughly 1 unit away from the origin.

**Comment by sjkelly** [comment]
@rdeits I added some tests. Thanks for fixing https://github.com/JuliaGeometry/Meshing.jl/issues/6 as well. It made getting this correct much simpler.

**Comment by sjkelly** [comment]
Closing in favor of #20

**Pull request closed without merging**
